name: OC-data-processed

on:
  push:
    branches:
      - main
  schedule:
     - cron: '0 */2 * * *'
permissions:
  contents: write
  
jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download CSV file
        run: |
          curl -O https://storage.googleapis.com/prod-geoservice-lightship/POIsLightshipDevPortal.csv

      - name: Remove EXPERIMENTAL line
        run: |
          sed -i '/EXPERIMENTAL/d' POIsLightshipDevPortal.csv

      - name: Run processed.py
        run: python processed.py
      
      - name: Append result to record.csv on count branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout count
          git pull origin count
          cat count.csv >> record.csv
          git add record.csv
          git commit -m "Update record.csv with processed data"
          git push origin count --force

      - name: Commit and push changes to gh-pages branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b gh-pages origin/gh-pages || git checkout --orphan gh-pages
          git add POIdb.csv
          git commit -m "Update CSV file"
          git push origin gh-pages --force
