name: OC-data-processed

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download CSV file
        run: |
          curl -O https://storage.googleapis.com/prod-geoservice-lightship/POIsLightshipDevPortal.csv

      - name: Remove EXPERIMENTAL line
        run: |
          sed -i '/EXPERIMENTAL/d' POIsLightshipDevPortal.csv

      - name: Run processed.py
        run: python processed.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add POIdb.csv
          git commit -m "Update CSV file"

      - name: Push changes to gh-pages branch
        uses: ad-m/github-push-action@v0.7.0
        with:
          branch: gh-pages
          github_token: ${{ secrets.GH_TOKEN }}
