name: OC-data-processed

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  process_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download CSV file
        run: |
          curl -O https://storage.googleapis.com/prod-geoservice-lightship/POIsLightshipDevPortal.csv

      - name: Remove EXPERIMENTAL line
        run: sed -i '/EXPERIMENTAL/d' POIsLightshipDevPortal.csv

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run processed.py
        run: python processed.py

      - name: Commit and push changes
        run: |
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_SECRET }}
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: upload

