name: OC-data-processed

on:
  push:
    branches:
      - main
  schedule:
     - cron: '0 */2 * * *'
permissions:
  contents: write
  
jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download CSV file
        run: |
          curl -O https://storage.googleapis.com/prod-geoservice-lightship/POIsLightshipDevPortal.csv

      - name: Remove EXPERIMENTAL line
        run: |
          sed -i '/EXPERIMENTAL/d' POIsLightshipDevPortal.csv

      - name: Run processed.py
        run: python processed.py
        
      - name: Read text file
        id: read-text
        run: |
          TEXT=$(cat count.csv)
          echo "Read TEXT: $TEXT"
          echo "TEXT=$TEXT" >> $GITHUB_ENV
      
      - name: Send to Telegram
        run: |
          curl -X POST  ${{ secrets.POST_URL }} \
            -d "chat_id=-1002083472369" \
            -d "text=${TEXT}"

            
      - name: Commit and push changes to gh-pages branch
        run: |
          wget https://github.com/Ingress-wiki/OverClocking-Map/raw/gh-pages/record.csv
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b gh-pages origin/gh-pages || git checkout --orphan gh-pages
          cat count.csv >> record.csv
          git add POIdb.csv
          git add record.csv
          git commit -m "Update CSV file"
          git push origin gh-pages --force
